// -------------------------------------------------------------------------
// PROJETO: CONNECTION CYBER PORTAL
// ARQUIVO: prisma.config.ts
// OBJETIVO: Centralização de Configurações Prisma v7
// GOVERNANÇA: PGT-01 (NORMA EXTREMO ZERO)
// -------------------------------------------------------------------------

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL || process.env["DATABASE_URL"],
  },
});